version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
        - "80:80" 
    volumes:
      - ../public/:/usr/share/nginx/html/
      - ./log_nginx/:/var/log/nginx/
    tty: true
